# Generated by Django 4.2.30 on 2026-08-20 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recycling.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recycling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard paper reward', max_length=120)),
                ('minimum_grams', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maximum_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RECYCLING', 'Recycling'), ('REWARD', 'Reward'), ('ACHIEVEMENT', 'Achievement'), ('MACHINE', 'Machine'), ('GOAL', 'Goal'), ('REDEMPTION', 'Redemption')], default='RECYCLING', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='recyclingsession',
            name='session_id',
            field=models.CharField(default=recycling.models.make_session_id, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='ONLINE', max_length=20),
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.PositiveIntegerField()),
                ('coupon_code', models.CharField(max_length=40, unique=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recycling.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MachineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling.machine')),
            ],
        ),
    ]
