# Generated by Django 4.2.30 on 2026-08-20 12:24

from django.db import migrations, models
import django.db.models.deletion
import recycling.models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0002_rewardrule_notification_type_profile_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(default=recycling.models.make_registration_id, max_length=32, unique=True)),
                ('rfid_uid', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('DETECTED', 'Detected'), ('LINKED', 'Linked'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recycling.machine')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling.profile')),
            ],
        ),
    ]
