# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycling", "0003_rfidregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
