# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recycling", "0004_alter_profile_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rfid_status",
            field=models.CharField(choices=[("ACTIVE", "Active"), ("BLOCKED", "Blocked")], default="ACTIVE", max_length=10),
        ),
    ]
